# Data sources
## Data description
Social Vulnerability Index: Statistical data of the relative vulnerability in the United States, including socio-economic status, minority, unemployment, etc

Source: https://catalog.data.gov/dataset/social-vulnerability-index-2018-united-states-county 

COVID-19 Deaths: The population of COVID-19 deaths by states and county around the United States

Source: https://wonder.cdc.gov/controller/datarequest/D76;jsessionid=594DDBB7A5D4544027ED97D7A7D5 

2021 COVID-19 Vaccine Attitudes among People Experiencing Homelessness in Los Angeles, CA: Data collected from a pilot mobile survey among homeless people in Los Angeles includes the demographic background, fear of COVID-19, attitudes of vaccination, etc

Source: https://www.openicpsr.org/openicpsr/project/140701/version/V3/view

Geographic Data: Geographic information of the United States in a shape file.

Source: https://www.census.gov/cgi-bin/geo/shapefiles/index.php


US State Vaccinations: The COVID-19 vaccination coverage by states and county around the United States

Source: https://github.com/owid/covid-19-data/blob/master/public/data/vaccinations/us_state_vaccinations.csv 

Data on COVID-19 Vaccinations by Race/Ethnicity: Percentage of total population who have received COVID-19 vaccine in the United States with race data gathered

Source: https://www.kff.org/coronavirus-covid-19/issue-brief/latest-data-on-covid-19-vaccinations-by-race-ethnicity/


```{r}
library(readxl)
library(tidyverse)
library(readr)
library(tmap)
library(sf)
library(redav)
library(mi)
library(tigris)

library(GGally)
library(ggpmisc)
library(gridExtra)
library(grid)
library(parcoords)
library(plotly)

library(vcd)
library(RColorBrewer)

setwd("C:\\Users\\joj\\Desktop\\data\\data")
shape <- read_sf("tl_2021_us_state\\tl_2021_us_state.shp")
sv <- read_csv("Social_Vulnerability_Index_2018_United_States_county.csv")
cov19_death <- read_tsv("covid_death.txt")
la <- read_excel("la_homeless_covid.xlsx")
vaccinated <- read_csv("us_state_vaccinations.csv")
vaccine_by_race <- read_csv("Percent of total pop has received a cov19 vaccine by race.csv")

```